<<<<<<< HEAD
# Generated by Django 2.0.4 on 2018-05-31 13:54
=======
# Generated by Django 2.0.4 on 2018-05-30 11:56
>>>>>>> ba898d240b6c7789d2cb4265dd573cc7b2a6fb67

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lists', '0005_list_item_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
